name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/antenbot:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |

            mkdir -p ~/antenbot
            cd ~/antenbot
            touch .env
            echo ${{ secrets.ENV_FILE }} >> .env
            # Pull the latest image
            docker pull ghcr.io/${{ github.repository_owner }}/antenbot:latest

            # Stop and remove the old container if it exists
            docker stop antenbot || true
            docker rm antenbot || true

            # Run the new container
            docker run -d \
              --name antenbot \
              --restart unless-stopped \
              -v $(pwd)/files:/app/files \
              -v $(pwd)/.env:/app/.env \
              ghcr.io/${{ github.repository_owner }}/antenbot:latest
